;;;###autoload
(define-generic-mode 'mainspring-graphviz-dot-mode
  '(("/*" . "*/"))
  '()
  '(("^digraph" . font-lock-keyword-face)
    (" -> " . font-lock-keyword-face)
    ("^ *graph " . font-lock-type-face)
    ("^ *node " . font-lock-type-face)
    ("^ *edge " . font-lock-type-face)
    ("\\(bgcolor\\)=" (1 font-lock-variable-name-face))
    ("\\(resolution\\)=" (1 font-lock-variable-name-face))
    ("\\(fontname\\)=" (1 font-lock-variable-name-face))
    ("\\(fontcolor\\)=" (1 font-lock-variable-name-face))
    ("\\(fontsize\\)=" (1 font-lock-variable-name-face))
    ("\\(color\\)=" (1 font-lock-variable-name-face))
    (" \\(.*\\) {" (1 font-lock-function-name-face))
    )
  '("\\.gv\\'")
  `(,(lambda () (setq mode-name "Dot Dir. Graph")))
  "Major mode for GraphViz Dot directed graph syntax highlighting.")

(provide 'mainspring-graphviz-dot-mode)
